import { app, safeStorage, shell } from "electron";
import crypto from "node:crypto";
import fs from "node:fs/promises";
import http from "node:http";
import path from "node:path";
import type { CloudflareConnectionStatus } from "../shared/cloudflare-auth";
import { cloudflareOAuthRedirectUri, cloudflareOAuthScopes } from "../shared/cloudflare-auth";

const AUTH_URL = "https://dash.cloudflare.com/oauth2/auth";
const TOKEN_URL = "https://dash.cloudflare.com/oauth2/token";
const USERINFO_URL = "https://dash.cloudflare.com/oauth2/userinfo";
const API_BASE = "https://api.cloudflare.com/client/v4";
const CALLBACK_PORT = 42831;
const CALLBACK_PATH = "/oauth/cloudflare/callback";

type StoredCloudflareSession = { encryptedAccessToken: string; encryptedRefreshToken?: string; expiresAt?: string; accountId?: string; accountName?: string; userEmail?: string };
type TokenResponse = { access_token: string; refresh_token?: string; expires_in?: number };

function base64Url(bytes: Buffer) { return bytes.toString("base64").replaceAll("+", "-").replaceAll("/", "_").replaceAll("=", ""); }
function getClientId() { return process.env.WHATABOUTIT_CLOUDFLARE_OAUTH_CLIENT_ID?.trim(); }
function getSessionPath() { return path.join(app.getPath("userData"), "cloudflare-session.json"); }
function encrypt(value: string) { if (!safeStorage.isEncryptionAvailable()) throw new Error("Secure operating-system credential storage is unavailable."); return safeStorage.encryptString(value).toString("base64"); }
function decrypt(value: string) { if (!safeStorage.isEncryptionAvailable()) throw new Error("Secure operating-system credential storage is unavailable."); return safeStorage.decryptString(Buffer.from(value, "base64")); }
async function readSession(): Promise<StoredCloudflareSession | undefined> { try { return JSON.parse(await fs.readFile(getSessionPath(), "utf8")) as StoredCloudflareSession; } catch { return undefined; } }
async function writeSession(session: StoredCloudflareSession) { await fs.mkdir(path.dirname(getSessionPath()), { recursive: true }); await fs.writeFile(getSessionPath(), JSON.stringify(session, null, 2), "utf8"); }
async function clearSession() { await fs.rm(getSessionPath(), { force: true }); }
async function fetchJson<T>(url: string, accessToken: string): Promise<T> { const response = await fetch(url, { headers: { Authorization: `Bearer ${accessToken}`, Accept: "application/json" } }); if (!response.ok) throw new Error(`Cloudflare request failed (${response.status}).`); return (await response.json()) as T; }
async function tokenRequest(body: URLSearchParams): Promise<TokenResponse> { const response = await fetch(TOKEN_URL, { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded", Accept: "application/json" }, body }); if (!response.ok) throw new Error(`Cloudflare token exchange failed (${response.status}).`); return (await response.json()) as TokenResponse; }
async function exchangeCode(code: string, codeVerifier: string) { const clientId = getClientId(); if (!clientId) throw new Error("Cloudflare OAuth client is not configured."); return tokenRequest(new URLSearchParams({ grant_type: "authorization_code", client_id: clientId, code, redirect_uri: cloudflareOAuthRedirectUri, code_verifier: codeVerifier })); }
async function refreshTokens(refreshToken: string) { const clientId = getClientId(); if (!clientId) throw new Error("Cloudflare OAuth client is not configured."); return tokenRequest(new URLSearchParams({ grant_type: "refresh_token", client_id: clientId, refresh_token: refreshToken })); }
async function hydrateIdentity(accessToken: string) { const userInfo = await fetchJson<Record<string, unknown>>(USERINFO_URL, accessToken); const accounts = await fetchJson<{ result?: Array<{ id: string; name: string }> }>(`${API_BASE}/accounts?per_page=50`, accessToken); const account = accounts.result?.[0]; return { userEmail: typeof userInfo.email === "string" ? userInfo.email : undefined, accountId: account?.id, accountName: account?.name }; }
function waitForCallback(expectedState: string): Promise<string> { return new Promise((resolve, reject) => { let settled = false; const server = http.createServer((request, response) => { try { const url = new URL(request.url ?? "/", `http://127.0.0.1:${CALLBACK_PORT}`); if (url.pathname !== CALLBACK_PATH) { response.writeHead(404).end("Not found"); return; } const error = url.searchParams.get("error"); const state = url.searchParams.get("state"); const code = url.searchParams.get("code"); if (error) throw new Error(`Cloudflare authorization was not completed: ${error}`); if (!state || state !== expectedState) throw new Error("Cloudflare authorization state did not match."); if (!code) throw new Error("Cloudflare did not return an authorization code."); response.writeHead(200, { "Content-Type": "text/html; charset=utf-8" }); response.end("<!doctype html><html><body style='font-family:system-ui;padding:40px'><h2>What About It is connected.</h2><p>You can close this browser tab and return to the app.</p></body></html>"); settled = true; server.close(); resolve(code); } catch (error) { response.writeHead(400, { "Content-Type": "text/plain; charset=utf-8" }).end(error instanceof Error ? error.message : "Authorization failed."); settled = true; server.close(); reject(error); } }); server.on("error", reject); server.listen(CALLBACK_PORT, "127.0.0.1"); setTimeout(() => { if (settled) return; settled = true; server.close(); reject(new Error("Cloudflare sign-in timed out. Please try again.")); }, 5 * 60 * 1000).unref(); }); }
async function persistTokens(tokens: TokenResponse, previous?: StoredCloudflareSession) { const identity = await hydrateIdentity(tokens.access_token); const expiresAt = tokens.expires_in ? new Date(Date.now() + tokens.expires_in * 1000).toISOString() : undefined; const session: StoredCloudflareSession = { encryptedAccessToken: encrypt(tokens.access_token), encryptedRefreshToken: tokens.refresh_token ? encrypt(tokens.refresh_token) : previous?.encryptedRefreshToken, expiresAt, ...identity }; await writeSession(session); return session; }
async function ensureFreshSession(): Promise<StoredCloudflareSession | undefined> { const session = await readSession(); if (!session) return undefined; const expiresSoon = Boolean(session.expiresAt && Date.parse(session.expiresAt) <= Date.now() + 60_000); if (!expiresSoon) return session; if (!session.encryptedRefreshToken) { await clearSession(); return undefined; } try { return await persistTokens(await refreshTokens(decrypt(session.encryptedRefreshToken)), session); } catch { await clearSession(); return undefined; } }
export async function getCloudflareConnectionStatus(): Promise<CloudflareConnectionStatus> { if (!getClientId()) return { state: "unconfigured", clientConfigured: false }; const session = await ensureFreshSession(); if (!session) return { state: "disconnected", clientConfigured: true }; return { state: "connected", clientConfigured: true, accountId: session.accountId, accountName: session.accountName, userEmail: session.userEmail, expiresAt: session.expiresAt }; }
export async function connectCloudflare(): Promise<CloudflareConnectionStatus> { const clientId = getClientId(); if (!clientId) return { state: "unconfigured", clientConfigured: false, error: "The What About It Cloudflare OAuth client has not been registered yet." }; const state = base64Url(crypto.randomBytes(24)); const verifier = base64Url(crypto.randomBytes(48)); const challenge = base64Url(crypto.createHash("sha256").update(verifier).digest()); const authorizationUrl = new URL(AUTH_URL); authorizationUrl.searchParams.set("response_type", "code"); authorizationUrl.searchParams.set("client_id", clientId); authorizationUrl.searchParams.set("redirect_uri", cloudflareOAuthRedirectUri); authorizationUrl.searchParams.set("state", state); authorizationUrl.searchParams.set("code_challenge", challenge); authorizationUrl.searchParams.set("code_challenge_method", "S256"); authorizationUrl.searchParams.set("scope", [...cloudflareOAuthScopes, "offline_access"].join(" ")); const callback = waitForCallback(state); await shell.openExternal(authorizationUrl.toString()); const code = await callback; await persistTokens(await exchangeCode(code, verifier)); return getCloudflareConnectionStatus(); }
export async function disconnectCloudflare(): Promise<CloudflareConnectionStatus> { await clearSession(); return { state: getClientId() ? "disconnected" : "unconfigured", clientConfigured: Boolean(getClientId()) }; }
export async function getCloudflareAccessToken(): Promise<string | undefined> { const session = await ensureFreshSession(); return session?.encryptedAccessToken ? decrypt(session.encryptedAccessToken) : undefined; }
