import { BrowserWindow } from "electron";

let collaborationWindow: BrowserWindow | undefined;

const collaborationHtml = `<!doctype html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>What About It — Collaboration</title><style>
:root{color-scheme:dark;font-family:Inter,system-ui,sans-serif;background:#160f10;color:#f7eee7}*{box-sizing:border-box}body{margin:0;background:#160f10}header{position:sticky;top:0;z-index:4;padding:20px 26px;background:#160f10f2;border-bottom:1px solid #4b3134;display:flex;justify-content:space-between;gap:16px}.shell{padding:20px 26px 36px;display:grid;grid-template-columns:290px minmax(0,1fr);gap:18px}.side,.card{background:#211719;border:1px solid #4b3134;border-radius:15px;padding:17px}.side{height:max-content;position:sticky;top:94px}.stack{display:grid;gap:14px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}h1,h2,h3,p{margin-top:0}.eyebrow{font-size:11px;font-weight:800;letter-spacing:.13em;text-transform:uppercase;color:#d9a46d}.muted{color:#b9a59d;font-size:13px;line-height:1.45}label{display:block;font-size:12px;color:#cbbab2;margin:11px 0 5px}input,select,textarea{width:100%;background:#120c0d;color:#fff;border:1px solid #654447;border-radius:9px;padding:9px 10px}textarea{min-height:86px}button{border:0;border-radius:9px;padding:9px 12px;background:#a64d49;color:#fff;font-weight:750;cursor:pointer}button.secondary{background:#3a292b}button.ghost{background:transparent;border:1px solid #654447}.row{display:flex;gap:8px;flex-wrap:wrap}.badge{display:inline-flex;border:1px solid #6c494d;border-radius:999px;padding:3px 8px;font-size:11px;margin:3px}.good{border-color:#4d725b;color:#bce7c9}.warn{border-color:#8a643e;color:#f4d7af}.asset,.comment,.member{padding:11px;border:1px solid #3c292c;border-radius:11px;background:#170f11}.asset{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px}.asset strong{overflow-wrap:anywhere}.safety{padding:11px;border:1px solid #4d725b;background:#173122;border-radius:11px;color:#d7f4df}.sync{padding:12px;border:1px solid #6c494d;border-radius:11px;background:#1a1113}.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.metric{padding:10px;border:1px solid #3c292c;border-radius:10px;background:#170f11}.metric strong{display:block;font-size:20px}.empty{padding:14px;border:1px dashed #4d3437;border-radius:10px;color:#9f8c85;text-align:center}@media(max-width:900px){.shell{grid-template-columns:1fr}.side{position:static}.grid{grid-template-columns:1fr}} </style></head><body>
<header><div><div class="eyebrow">What About It Studio</div><h1>Episode Collaboration</h1><div class="muted">Shared review, edit handoff, files and Cloudflare sync</div></div><span id="cloudBadge" class="badge warn">Checking cloud…</span></header>
<div class="shell"><aside class="side"><div class="eyebrow">Episode library</div><label>Episode</label><select id="episode"></select><div id="summary" class="muted" style="margin-top:9px"></div><div class="row" style="margin-top:10px"><button id="openFolder" class="secondary">Open folder</button><button id="refresh" class="ghost">Refresh</button></div><hr style="border:0;border-top:1px solid #3c292c;margin:16px 0"><div class="safety"><strong>Originals stay local and protected</strong><div class="muted" style="color:#cce9d4;margin-top:5px">Cloud sync copies project data and only uploads full media when you choose it.</div></div><label>Review status</label><select id="status"><option value="working">Working</option><option value="ready-for-review">Ready for review</option><option value="changes-requested">Changes requested</option><option value="approved">Approved</option></select></aside>
<main class="stack"><section class="card"><div class="eyebrow">Current episode</div><h2 id="title">No episode selected</h2><div class="metrics"><div class="metric"><strong id="assetCount">0</strong><span class="muted">files</span></div><div class="metric"><strong id="originalCount">0</strong><span class="muted">protected originals</span></div><div class="metric"><strong id="commentCount">0</strong><span class="muted">open comments</span></div></div></section>
<section class="card"><div class="eyebrow">Cloudflare sync</div><h2>Sync this episode</h2><p class="muted">Timeline saves automatically sync project data. Use this when you want to push proxies or a full media backup too.</p><div class="grid"><div><label>Upload mode</label><select id="uploadMode"><option value="project-only">Project only — edits/comments/captions</option><option value="project-and-proxies">Project + editing proxies</option><option value="full-backup">Full episode backup</option></select></div><div style="display:flex;align-items:end;gap:8px"><button id="syncNow" style="width:100%">Sync now</button><button id="cancelSync" class="secondary" hidden>Cancel</button></div></div><div id="syncMessage" class="sync muted" style="margin-top:12px">Automatic project sync is on when Cloudflare is configured.</div></section>
<section class="card"><div class="row" style="justify-content:space-between;align-items:center"><div><div class="eyebrow">Episode files</div><h2 style="margin-bottom:0">Everything attached to this episode</h2></div><button id="scan" class="secondary">Scan files</button></div><div id="assets" class="stack" style="margin-top:12px"></div></section>
<div class="grid"><section class="card"><div class="eyebrow">People</div><h2>Collaborators</h2><div id="members" class="stack"></div><label>Name</label><input id="name" placeholder="Susan"><label>Email</label><input id="email" placeholder="Optional"><label>Role</label><select id="role"><option value="editor">Editor</option><option value="reviewer">Reviewer</option></select><button id="invite" style="margin-top:10px">Add collaborator</button></section>
<section class="card"><div class="eyebrow">Review</div><h2>Comments</h2><textarea id="comment" placeholder="Leave an edit or review note…"></textarea><button id="addComment" style="margin-top:9px">Post comment</button><div id="comments" class="stack" style="margin-top:12px"></div></section></div></main></div>
<script>
const studio=window.studio;const q=id=>document.getElementById(id);let workspace,activeTransferId;const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll(String.fromCharCode(34),'&quot;');const bytes=n=>{if(!n)return'0 B';const u=['B','KB','MB','GB','TB'];let v=n,i=0;while(v>=1024&&i<u.length-1){v/=1024;i++}return v.toFixed(i?1:0)+' '+u[i]};studio.onCloudTransferProgress?.(p=>{activeTransferId=p.operationId;const percent=p.totalBytes?Math.min(100,Math.round(p.transferredBytes/p.totalBytes*100)):0;q('syncMessage').textContent=p.message+' '+p.completedAssets+'/'+p.totalAssets+' files · '+percent+'%';q('cancelSync').hidden=['complete','cancelled','error'].includes(p.phase)});
function render(w){workspace=w;q('title').textContent=w.episodeTitle;q('status').value=w.status;const a=w.assets||[];q('assetCount').textContent=a.length;q('originalCount').textContent=a.filter(x=>x.localOriginal).length;q('commentCount').textContent=w.comments.filter(x=>!x.resolvedAt).length;q('summary').textContent='Updated '+new Date(w.updatedAt).toLocaleString();q('cloudBadge').textContent=w.remoteState==='ready'?'Cloudflare connected':'Cloudflare '+w.remoteState;q('cloudBadge').className='badge '+(w.remoteState==='ready'?'good':'warn');q('assets').innerHTML=a.length?a.map(x=>'<div class="asset"><div><strong>'+esc(x.relativePath)+'</strong><div><span class="badge">'+esc(x.kind)+'</span>'+(x.localOriginal?'<span class="badge good">original protected</span>':'')+'<span class="badge">'+esc(x.state)+'</span></div></div><span class="muted">'+bytes(x.bytes)+'</span></div>').join(''):'<div class="empty">No files indexed yet.</div>';q('members').innerHTML=w.members.map(m=>'<div class="member"><strong>'+esc(m.name)+'</strong><div class="muted">'+esc(m.email||m.role)+'</div><span class="badge">'+esc(m.role)+'</span></div>').join('');const names=Object.fromEntries(w.members.map(m=>[m.id,m.name]));const comments=w.comments.filter(c=>!c.resolvedAt).slice().reverse();q('comments').innerHTML=comments.length?comments.map(c=>'<div class="comment"><strong>'+esc(names[c.authorMemberId]||'Collaborator')+'</strong><div class="muted">'+new Date(c.createdAt).toLocaleString()+'</div><p>'+esc(c.body)+'</p><button class="secondary resolve" data-id="'+esc(c.id)+'">Resolve</button></div>').join(''):'<div class="empty">No open comments.</div>';document.querySelectorAll('.resolve').forEach(b=>b.onclick=async()=>render(await studio.resolveCollaborationComment(w.episodeId,b.dataset.id)));}
async function load(){const id=q('episode').value;if(id)render(await studio.getCollaborationWorkspace(id));}
async function boot(){const cfg=await studio.getCollaborationRemoteConfig();q('cloudBadge').textContent=cfg.apiUrl?'Cloudflare configured':'Cloudflare not configured';const episodes=await studio.listEpisodes();q('episode').innerHTML=episodes.map(e=>'<option value="'+esc(e.id)+'">'+esc(e.title)+'</option>').join('');if(episodes.length)await load();else q('summary').textContent='Create or import an episode first.';}
q('episode').onchange=load;q('refresh').onclick=load;q('openFolder').onclick=async()=>workspace&&studio.openCollaborationEpisodeFolder(workspace.episodeId);q('scan').onclick=async()=>workspace&&render(await studio.refreshCollaborationAssets(workspace.episodeId));q('cancelSync').onclick=async()=>{if(activeTransferId){await studio.cancelCloudTransfer(activeTransferId);q('syncMessage').textContent='Cancelling safely after the current protected chunk…'}};q('syncNow').onclick=async()=>{if(!workspace)return;const button=q('syncNow');button.disabled=true;q('syncMessage').textContent='Syncing changed files to Cloudflare…';try{const result=await studio.uploadEpisodeToCloud(workspace.episodeId,q('uploadMode').value);q('syncMessage').textContent=result.message;render(await studio.getCollaborationWorkspace(workspace.episodeId));}catch(e){q('syncMessage').textContent='Sync failed: '+e.message}finally{button.disabled=false;q('cancelSync').hidden=true}};q('status').onchange=async()=>workspace&&render(await studio.setCollaborationStatus(workspace.episodeId,q('status').value));q('invite').onclick=async()=>{if(!workspace||!q('name').value.trim())return;render(await studio.inviteCollaborator(workspace.episodeId,{name:q('name').value.trim(),email:q('email').value.trim()||undefined,role:q('role').value}));q('name').value='';q('email').value=''};q('addComment').onclick=async()=>{if(!workspace||!q('comment').value.trim())return;const self=workspace.members.find(m=>m.status==='active')||workspace.members[0];render(await studio.addCollaborationComment(workspace.episodeId,{authorMemberId:self.id,body:q('comment').value.trim()}));q('comment').value=''};boot().catch(e=>q('summary').textContent='Could not load collaboration: '+e.message);
</script></body></html>`;

export function openCollaborationWindow(preloadPath: string) {
  if (collaborationWindow && !collaborationWindow.isDestroyed()) {
    collaborationWindow.focus();
    return collaborationWindow;
  }
  collaborationWindow = new BrowserWindow({
    width: 1180,
    height: 820,
    minWidth: 800,
    minHeight: 640,
    title: "What About It — Collaboration",
    backgroundColor: "#160f10",
    webPreferences: { preload: preloadPath, contextIsolation: true, nodeIntegration: false }
  });
  collaborationWindow.on("closed", () => { collaborationWindow = undefined; });
  void collaborationWindow.loadURL(`data:text/html;charset=UTF-8,${encodeURIComponent(collaborationHtml)}`);
  return collaborationWindow;
}
