import { BrowserWindow } from "electron";

let presenceWindow: BrowserWindow | undefined;

const html = `<!doctype html><html><head><meta charset="UTF-8"><title>What About It — Live Collaboration</title><style>
body{font-family:Inter,system-ui,sans-serif;background:#160f10;color:#f7eee7;margin:0;padding:24px}.card{background:#211719;border:1px solid #4b3134;border-radius:16px;padding:18px;margin-bottom:14px}label{display:block;font-size:12px;color:#cbbab2;margin:12px 0 6px}input,select,button{font:inherit}input,select{width:100%;box-sizing:border-box;background:#120c0d;color:#fff7ef;border:1px solid #654447;border-radius:10px;padding:10px}button{border:0;border-radius:10px;padding:10px 14px;background:#a64d49;color:#fff;font-weight:700;cursor:pointer;margin-right:8px}.secondary{background:#3a292b}.person{display:flex;justify-content:space-between;padding:10px 0;border-bottom:1px solid #3c292c}.badge{padding:3px 8px;border:1px solid #6c494d;border-radius:999px;font-size:12px}.good{border-color:#4d725b;color:#bce7c9}.warn{border-color:#8a643e;color:#f4d7af}.muted{color:#ae9b93;font-size:13px}.row{display:flex;gap:10px}.row>*{flex:1}</style></head><body>
<h1>Live Collaboration</h1><p class="muted">One timeline editor at a time. Both people can still review and comment.</p>
<div class="card"><div class="row"><div><label>Who is using this computer?</label><select id="person"><option value="morgan-owner">Morgan</option><option value="susan-editor">Susan</option></select></div><div><label>Episode</label><select id="episode"></select></div></div><label>Collaboration service URL</label><input id="apiUrl" placeholder="https://whataboutit-collab.<account>.workers.dev"><label>Collaboration key</label><input id="accessKey" type="password" placeholder="Shared What About It app key"><div style="margin-top:12px"><button id="saveConfig">Save connection</button><button id="refresh" class="secondary">Refresh</button></div></div>
<div class="card"><h2 id="editor">No active editor</h2><div id="people"></div><div style="margin-top:14px"><button id="take">Start editing</button><button id="release" class="secondary">Release edit control</button></div><p id="status" class="muted"></p></div>
<script>
const studio=window.studio;const q=id=>document.getElementById(id);let snapshot;let timer;
function render(s){snapshot=s;q('editor').textContent=s.activeEditor?s.activeEditor.displayName+' is editing':'No active editor';q('people').innerHTML=s.people.map(p=>'<div class="person"><strong>'+p.displayName+'</strong><span class="badge '+(p.mode==='editing'?'good':p.mode==='viewing'?'':'warn')+'">'+p.mode+'</span></div>').join('');q('status').textContent=s.error||('You are '+s.self.displayName+'. '+(s.canEdit?'Edit control available.':'Timeline locked by '+s.activeEditor?.displayName+'.'));q('take').disabled=!s.canEdit||s.activeEditor?.memberId===s.self.memberId;q('release').disabled=s.activeEditor?.memberId!==s.self.memberId;}
async function heartbeat(){const episodeId=q('episode').value;if(!episodeId)return;try{const current=await studio.getCollaborationPresence(episodeId);if(current.activeEditor?.memberId===current.self.memberId) render(await studio.heartbeatCollaborationEditorLease(episodeId));else render(await studio.heartbeatCollaborationPresence(episodeId,'viewing'));}catch(e){q('status').textContent=e.message;}}
async function boot(){const cfg=await studio.getCollaborationRemoteConfig();q('person').value=cfg.personId;q('apiUrl').value=cfg.apiUrl||'';q('accessKey').value=cfg.accessKey||'';const episodes=await studio.listEpisodes();q('episode').innerHTML=episodes.map(e=>'<option value="'+e.id+'">'+e.title+'</option>').join('');await heartbeat();timer=setInterval(heartbeat,10000);}
q('saveConfig').onclick=async()=>{await studio.setCollaborationRemoteConfig({personId:q('person').value,apiUrl:q('apiUrl').value,accessKey:q('accessKey').value});await heartbeat();};q('refresh').onclick=heartbeat;q('take').onclick=async()=>render(await studio.acquireCollaborationEditorLease(q('episode').value));q('release').onclick=async()=>render(await studio.releaseCollaborationEditorLease(q('episode').value));q('episode').onchange=heartbeat;q('person').onchange=async()=>{await studio.setCollaborationRemoteConfig({personId:q('person').value});await heartbeat();};window.addEventListener('beforeunload',()=>{clearInterval(timer);if(q('episode').value)void studio.leaveCollaborationPresence(q('episode').value);});boot();
</script></body></html>`;

export function openCollaborationPresenceWindow(preloadPath: string) {
  if (presenceWindow && !presenceWindow.isDestroyed()) { presenceWindow.focus(); return presenceWindow; }
  presenceWindow = new BrowserWindow({ width: 720, height: 720, minWidth: 620, minHeight: 580, title: "What About It — Live Collaboration", backgroundColor: "#160f10", webPreferences: { preload: preloadPath, contextIsolation: true, nodeIntegration: false } });
  presenceWindow.on("closed", () => { presenceWindow = undefined; });
  void presenceWindow.loadURL(`data:text/html;charset=UTF-8,${encodeURIComponent(html)}`);
  return presenceWindow;
}
